### ISSUE TITLE
@nowarn annotation does not suppress any warnings (200USD Bounty)

### ISSUE THREAD

**Issue by soufianexmx** [com-lihaoyi/fastparse#285] opened 2023-04-26 08:51 UTC
Using Scala 2.13, after upgrading to version 3.0.1, for a code like:
```
private def string[A: P]: P[String]   = P(CharIn("a-zA-Z0-9").rep(1).!)
```
we get compilation error:
```
@nowarn annotation does not suppress any warnings
```

**Haoyi**: To incentivize contribution, I'm putting a 200USD bounty on resolving this ticket. This is payable via bank transfer, and at my discretion in case of ambiguity. The acceptance criteria is a PR fixing this issue and updates to our test infrastructure to validate the fix

**Comment by limansky** [comment] 2023-05-19 23:03
Same here. Reproduces both with Scala 2.13.10 and 3.2.2

**Comment by SethTisue** [comment] 2023-06-29 14:23
presumably this started with https://github.com/com-lihaoyi/fastparse/pull/281

**Comment by SethTisue** [comment] 2023-06-29 14:33
if someone is looking for a workaround, I think "`@nowarn` annotation does not suppress any warning" is itself a warning that can be suppressed with `@nowarn`?

**Comment by fanf** [comment] 2023-06-29 15:12
I wasn't able to find an other way than disabling useless nowarn warning with `-Wconf:cat=unused-nowarn:s` (see https://www.scala-lang.org/api/current/scala/annotation/nowarn.html). 
I would prefer that scalac don't report nowarn inside macro, because as the user of the macro, I can't do anything about them.

**Comment by fanf** [comment] 2023-06-30 08:22
So, one can selectively silent the problematic warning on specific file but keep them for other files with combined filter. 
For ex:
```-Wconf:cat=unused-nowarn&src=com/normation/utils/Version.scala:s,cat=unused-nowarn&src=com/normation/rudder/services/policies/InterpolatedValueCompiler.scala:s```

Will silent the `@nowarn annotation does not suppress any warnings` warnings in `com/normation/utils/Version.scala` and `com/normation/rudder/services/policies/InterpolatedValueCompiler.scala`, but keep them in other files. 
More info with `scala -Wconf:help`

This is good enought for the time being for me.

**Comment by lihaoyi** [comment] 2023-07-10 01:34
Somehow I'm not able to reproduce this inside my test suite. Would appreciate any help if someone wants to look into this inside the Fastparse repo and come up with a repro

**Comment by kitbellew** [comment] 2023-07-10 03:29
@lihaoyi I don't know if this is related, but here's the error I got for 2.13.1 (and only that version): https://github.com/scalameta/scalameta/actions/runs/5503580335/jobs/10028930479?pr=3246

**Comment by lihaoyi** [comment] 2023-07-10 05:36
Maybe it's specific to particular Scala versions? @soufianexmx @limansky @fanf what Scala versions are you guys seeing this in?

**Comment by Bathtor** [comment] 2023-07-10 07:30
2.13.10 for me I think.

**Comment by fanf** [comment] 2023-07-10 08:27
We first saw it in 2.13.10, and I checked it's still the case in 2.13.11

**Comment by lihaoyi** [comment] 2023-08-08 02:31
Ah I think it must be the `-Xlint` flag that I've been missing

**Comment by limansky** [comment] 2023-10-20 14:41
@lihaoyi 
Hi, I've checked 3.0.2 and the issue is still there. Please let me know if you need minimal example to demonstrate the problem.

**Comment by He-Pin** [comment] 2024-05-15 06:11
I'm using Fastparse too in a Java project, I would like to take this a try.

**Comment by lihaoyi** [comment] 2024-05-17 00:17
@He-Pin  please go ahead!

**Comment by lihaoyi** [comment] 2024-05-19 07:50
Should be fixed by https://github.com/com-lihaoyi/fastparse/pull/310

**Closed by lihaoyi** 2024-05-19 07:50 UTC

**Comment by SethTisue** [comment] 2024-05-20 18:37
👏
